package com.zh.domain;

/**
 * course_type
 * 
 * @author bianj
 * @version 1.0.0 2020-09-16
 */
public class CourseType implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3660126451844249962L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String typeName;

    /** flag */
    private Byte flag;

    public CourseType(Integer id, String typeName, Byte flag) {
        this.id = id;
        this.typeName = typeName;
        this.flag = flag;
    }
    public CourseType(){}


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Byte getFlag() {
        return flag;
    }

    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}