package com.zh.domain;

/**
 * course_type
 * 
 * @author bianj
 * @version 1.0.0 2020-09-16
 */
public class CourseType implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3660126451844249962L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;
    /** flag */
    private Integer flag;
    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public CourseType(Integer id, String name, Integer flag) {
        this.id = id;
        this.name = name;
        this.flag = flag;
    }




}